# files_in and file_out is MANDATORY due to `write_configs()`
files_in    = '/path/to/dir/in/'
file_out   = '/path/to/dir/out/'
run_number  = 00000

# optional arguments here
rebin_d     = [5, 5, 4]
drop_dist   = [16, 16, 4]
nhits       = 3
