global:
    tag              : 'test_1525'
    cluster_sys      : 'SLURM'
    verbose          : 1
    processing_style : 'LDC' # LDC, FOLDER, FILE
    LDCs             : 7
    RUNS             : ['00000', '00001'] 
    flow_priority    : 'JOB'   # either RUN or JOB
    # RUN prio means it will complete all jobs for a run first
    # JOB prio means it will complete the job for all runs first
    #global_path     : '/home/e78368jw/Documents/NEXT_CODE/production/test_data'
    global_path      : '/home/e78368jw/Documents/NEXT_CODE/production/test_data/example_data/'
    # global path is where your data is stored
    max_num_jobs     : 7
    env_script       : 'home/e78368jw/Documents/NEXT_CODE/production/templates/env_templates/dipc_helena.sh'



IC-beersheba:
    city              : 'beersheba'
    # these are for input, output from the global_path
    pre_path          : '/home/e78368jw/Documents/NEXT_CODE/production/test_data/example_data/' 
    post_path         : 'sophronia/'
    # f'{pre_path}{RUN_NUMBER}/{post_path}'
    fixed:
        compression      : "'ZLIB4'" # strings need to be referred to as such
        e_cut            : 0.1,
        threshold        : 2 * pes 
        same_peak        : True
        q_cut            : 50,
            
# i will need to set more of these

move_files_IC:
    job              : False # defines whether or not the job is scheduled or ran on the local machine
    fixed:
        old_path         : '/home/e78368jw/Documents/NEXT_CODE/production/test_data/example_data/'
        new_path         : '/home/e78368jw/Documents/NEXT_CODE/production/test_data/example_data/moving_data/'
        city             : 'beersheba' # where you're extracting it from
   

# this part isnt done
#
IC-isaura:
    city             : 'isaura'
    in_path          : 'beersheba.h5'
    fixed:
        voxel_size       : [15, 15, 15]
