global:
    tag              : 'test_1525'
    verbose          : 1
    processing_style : 'LDC' # LDC, FOLDER, FILE
    LDCs             : 7
    RUNS             : ['00000', '00001'] 
    flow_priority    : 'JOB'   # either RUN or JOB
    # RUN prio means it will complete all jobs for a run first
    # JOB prio means it will complete the job for all runs first
    global_path      : '/home/e78368jw/Documents/NEXT_CODE/production/test_data'
    # the global path works on the idea of:
    # data_dir/binary_of_relevance/RUN_NUMBER/TIMESTAMP/LDC/DATA.h5
    config_location  : 'configs' # based on global_path
    max_num_jobs     : 7


IC-beersheba:
    city             : 'beersheba'
    e_cut            : [0.1, 0.2, 0.3]
    n_iter           : [10, 20, 30]
    inner_dict       : {key: value, abc: def}
# i will need to set more of these

move_files:
    IC               : True
    input            : 'beersheba'
    output           : 'isaura'

IC-isaura:
    city             : 'isaura'
    in_path          : 'beersheba.h5'
    voxel_size       : [15, 15, 15]

